// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control_service.proto

#include "control_service.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace control {

inline constexpr ControlMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : args_{},
        command_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ControlMessage::ControlMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ControlMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ControlMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ControlMessageDefaultTypeInternal() {}
  union {
    ControlMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ControlMessageDefaultTypeInternal _ControlMessage_default_instance_;
}  // namespace control
static ::_pb::Metadata file_level_metadata_control_5fservice_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_control_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_control_5fservice_2eproto = nullptr;
const ::uint32_t TableStruct_control_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::control::ControlMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::control::ControlMessage, _impl_.command_name_),
    PROTOBUF_FIELD_OFFSET(::control::ControlMessage, _impl_.args_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::control::ControlMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::control::_ControlMessage_default_instance_._instance,
};
const char descriptor_table_protodef_control_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025control_service.proto\022\007control\"4\n\016Cont"
    "rolMessage\022\024\n\014command_name\030\001 \001(\t\022\014\n\004args"
    "\030\002 \003(\t2W\n\016ControlService\022E\n\rStreamContro"
    "l\022\027.control.ControlMessage\032\027.control.Con"
    "trolMessage(\0010\001B\016Z\014./service-gob\006proto3"
};
static ::absl::once_flag descriptor_table_control_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_5fservice_2eproto = {
    false,
    false,
    199,
    descriptor_table_protodef_control_5fservice_2eproto,
    "control_service.proto",
    &descriptor_table_control_5fservice_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_control_5fservice_2eproto::offsets,
    file_level_metadata_control_5fservice_2eproto,
    file_level_enum_descriptors_control_5fservice_2eproto,
    file_level_service_descriptors_control_5fservice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_5fservice_2eproto_getter() {
  return &descriptor_table_control_5fservice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_5fservice_2eproto(&descriptor_table_control_5fservice_2eproto);
namespace control {
// ===================================================================

class ControlMessage::_Internal {
 public:
};

ControlMessage::ControlMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:control.ControlMessage)
}
inline PROTOBUF_NDEBUG_INLINE ControlMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : args_{visibility, arena, from.args_},
        command_name_(arena, from.command_name_),
        _cached_size_{0} {}

ControlMessage::ControlMessage(
    ::google::protobuf::Arena* arena,
    const ControlMessage& from)
    : ::google::protobuf::Message(arena) {
  ControlMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:control.ControlMessage)
}
inline PROTOBUF_NDEBUG_INLINE ControlMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : args_{visibility, arena},
        command_name_(arena),
        _cached_size_{0} {}

inline void ControlMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ControlMessage::~ControlMessage() {
  // @@protoc_insertion_point(destructor:control.ControlMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ControlMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.command_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ControlMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:control.ControlMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.args_.Clear();
  _impl_.command_name_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ControlMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> ControlMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ControlMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated string args = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.args_)}},
    // string command_name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.command_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string command_name = 1;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.command_name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string args = 2;
    {PROTOBUF_FIELD_OFFSET(ControlMessage, _impl_.args_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\26\14\4\0\0\0\0\0"
    "control.ControlMessage"
    "command_name"
    "args"
  }},
};

::uint8_t* ControlMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:control.ControlMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string command_name = 1;
  if (!this->_internal_command_name().empty()) {
    const std::string& _s = this->_internal_command_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "control.ControlMessage.command_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // repeated string args = 2;
  for (int i = 0, n = this->_internal_args_size(); i < n; ++i) {
    const auto& s = this->_internal_args().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "control.ControlMessage.args");
    target = stream->WriteString(2, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:control.ControlMessage)
  return target;
}

::size_t ControlMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:control.ControlMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string args = 2;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_args().size());
  for (int i = 0, n = _internal_args().size(); i < n; ++i) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
        _internal_args().Get(i));
  }
  // string command_name = 1;
  if (!this->_internal_command_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_command_name());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ControlMessage::_class_data_ = {
    ControlMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ControlMessage::GetClassData() const {
  return &_class_data_;
}

void ControlMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ControlMessage*>(&to_msg);
  auto& from = static_cast<const ControlMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:control.ControlMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_args()->MergeFrom(from._internal_args());
  if (!from._internal_command_name().empty()) {
    _this->_internal_set_command_name(from._internal_command_name());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ControlMessage::CopyFrom(const ControlMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:control.ControlMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ControlMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ControlMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ControlMessage::InternalSwap(ControlMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.args_.InternalSwap(&other->_impl_.args_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.command_name_, &other->_impl_.command_name_, arena);
}

::google::protobuf::Metadata ControlMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_5fservice_2eproto_getter, &descriptor_table_control_5fservice_2eproto_once,
      file_level_metadata_control_5fservice_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace control
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
