// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control_service.proto
#ifndef GRPC_control_5fservice_2eproto__INCLUDED
#define GRPC_control_5fservice_2eproto__INCLUDED

#include "control_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace control {

// The ControlService provides a bidirectional streaming RPC.
class ControlService final {
 public:
  static constexpr char const* service_full_name() {
    return "control.ControlService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // StreamControl allows sending and receiving ControlMessages.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>> StreamControl(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>>(StreamControlRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>> AsyncStreamControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>>(AsyncStreamControlRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>> PrepareAsyncStreamControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>>(PrepareAsyncStreamControlRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // StreamControl allows sending and receiving ControlMessages.
      virtual void StreamControl(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::control::ControlMessage,::control::ControlMessage>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>* StreamControlRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>* AsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::control::ControlMessage, ::control::ControlMessage>* PrepareAsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::control::ControlMessage, ::control::ControlMessage>> StreamControl(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::control::ControlMessage, ::control::ControlMessage>>(StreamControlRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>> AsyncStreamControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>>(AsyncStreamControlRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>> PrepareAsyncStreamControl(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>>(PrepareAsyncStreamControlRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamControl(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::control::ControlMessage,::control::ControlMessage>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* StreamControlRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* AsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* PrepareAsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamControl_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // StreamControl allows sending and receiving ControlMessages.
    virtual ::grpc::Status StreamControl(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamControl() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamControl(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamControl(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamControl<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamControl() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::control::ControlMessage, ::control::ControlMessage>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamControl(context); }));
    }
    ~WithCallbackMethod_StreamControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamControl(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::control::ControlMessage, ::control::ControlMessage>* StreamControl(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_StreamControl<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamControl() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamControl(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamControl() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamControl(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamControl(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamControl : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamControl() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->StreamControl(context); }));
    }
    ~WithRawCallbackMethod_StreamControl() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamControl(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* StreamControl(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace control


#endif  // GRPC_control_5fservice_2eproto__INCLUDED
