// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control_service.proto

#include "control_service.pb.h"
#include "control_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace control {

static const char* ControlService_method_names[] = {
  "/control.ControlService/StreamControl",
};

std::unique_ptr< ControlService::Stub> ControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControlService::Stub> stub(new ControlService::Stub(channel, options));
  return stub;
}

ControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamControl_(ControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* ControlService::Stub::StreamControlRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::control::ControlMessage, ::control::ControlMessage>::Create(channel_.get(), rpcmethod_StreamControl_, context);
}

void ControlService::Stub::async::StreamControl(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::control::ControlMessage,::control::ControlMessage>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::control::ControlMessage,::control::ControlMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamControl_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* ControlService::Stub::AsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::control::ControlMessage, ::control::ControlMessage>::Create(channel_.get(), cq, rpcmethod_StreamControl_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* ControlService::Stub::PrepareAsyncStreamControlRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::control::ControlMessage, ::control::ControlMessage>::Create(channel_.get(), cq, rpcmethod_StreamControl_, context, false, nullptr);
}

ControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ControlService::Service, ::control::ControlMessage, ::control::ControlMessage>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::control::ControlMessage,
             ::control::ControlMessage>* stream) {
               return service->StreamControl(ctx, stream);
             }, this)));
}

ControlService::Service::~Service() {
}

::grpc::Status ControlService::Service::StreamControl(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::control::ControlMessage, ::control::ControlMessage>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace control

