// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: control_service.proto

package service_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ControlService_StreamControl_FullMethodName = "/control.ControlService/StreamControl"
)

// ControlServiceClient is the client API for ControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlServiceClient interface {
	// StreamControl allows sending and receiving ControlMessages.
	StreamControl(ctx context.Context, opts ...grpc.CallOption) (ControlService_StreamControlClient, error)
}

type controlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlServiceClient(cc grpc.ClientConnInterface) ControlServiceClient {
	return &controlServiceClient{cc}
}

func (c *controlServiceClient) StreamControl(ctx context.Context, opts ...grpc.CallOption) (ControlService_StreamControlClient, error) {
	stream, err := c.cc.NewStream(ctx, &ControlService_ServiceDesc.Streams[0], ControlService_StreamControl_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &controlServiceStreamControlClient{stream}
	return x, nil
}

type ControlService_StreamControlClient interface {
	Send(*ControlMessage) error
	Recv() (*ControlMessage, error)
	grpc.ClientStream
}

type controlServiceStreamControlClient struct {
	grpc.ClientStream
}

func (x *controlServiceStreamControlClient) Send(m *ControlMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controlServiceStreamControlClient) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlServiceServer is the server API for ControlService service.
// All implementations must embed UnimplementedControlServiceServer
// for forward compatibility
type ControlServiceServer interface {
	// StreamControl allows sending and receiving ControlMessages.
	StreamControl(ControlService_StreamControlServer) error
	mustEmbedUnimplementedControlServiceServer()
}

// UnimplementedControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedControlServiceServer struct {
}

func (UnimplementedControlServiceServer) StreamControl(ControlService_StreamControlServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamControl not implemented")
}
func (UnimplementedControlServiceServer) mustEmbedUnimplementedControlServiceServer() {}

// UnsafeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServiceServer will
// result in compilation errors.
type UnsafeControlServiceServer interface {
	mustEmbedUnimplementedControlServiceServer()
}

func RegisterControlServiceServer(s grpc.ServiceRegistrar, srv ControlServiceServer) {
	s.RegisterService(&ControlService_ServiceDesc, srv)
}

func _ControlService_StreamControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControlServiceServer).StreamControl(&controlServiceStreamControlServer{stream})
}

type ControlService_StreamControlServer interface {
	Send(*ControlMessage) error
	Recv() (*ControlMessage, error)
	grpc.ServerStream
}

type controlServiceStreamControlServer struct {
	grpc.ServerStream
}

func (x *controlServiceStreamControlServer) Send(m *ControlMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controlServiceStreamControlServer) Recv() (*ControlMessage, error) {
	m := new(ControlMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControlService_ServiceDesc is the grpc.ServiceDesc for ControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.ControlService",
	HandlerType: (*ControlServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamControl",
			Handler:       _ControlService_StreamControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control_service.proto",
}
